num1 = int(input("Digite um número: "))
num2 = int(input("Digite um número: "))
print("  ")
print("Soma:", num1 + num2)
print("Subtração: ", num1 - num2)
print("Divisão: ", num1 / num2)
print("Mulitplicação: ", num1 * num2)
print("Subtração reversa: ", num2 - num1)
print("Divisão reversa: ", num2 / num1)
print("Raiz quadrada de", num1, "é", num1**(1/2))
print("Raiz cúbica de", num1, "é", num1**(1/3))
print("Raiz quadrada de", num2, "é", num2**(1/2))
print("Raiz cúbica de", num2, "é", num2**(1/3))
