print("Bem vindo a tabela de aulas!")
print("  ")
segunda = input("Que aula tem na segunda-feira?: ")
terça = input("Que aula tem na terça-feira?: ")
quarta = input("Que aula tem na quarta-feira?: ")
quinta = input("Que aula tem na quinta-feira?: ")
sexta = input("Que aula tem na sexta-feira?: ")
print("  ")
print("DIA \t\t\t AULA")
print("================================")
print("Segunda-Feira \t", segunda)
print("Terça-Feira \t", terça)
print("Quarta-Feira \t", quarta)
print("Quinta-Feira \t", quinta)
print("Sexta-Feira \t", sexta)
